### DISCUSSION TITLE
Zero-downtime reindexing

### DISCUSSION THREAD

**Discussion by kbond** [schranz-search/schranz-search#198] [Ideas]
My app has a simple search system that I fully re-index in a cron job. This project looks very interesting! Currently, I'm using elasticsearch but looking to switch to algolia.

To avoid downtime during the re-index, I have two indexes that I swap between with an alias.

Algolia has a similar feature: https://www.algolia.com/doc/api-reference/api-methods/replace-all-objects/

Curious if there is interest in this feature in SEAL. Maybe a `ReindexableSchemaManagerInterface`?

**Comment by alexander-schranz** [comment]
Hello @kbond,

That is sure an interesting idea and aliases are something I already had on my list because I also think it make reindexing easier. The algolias `replaceAll` looks a little bit strange for me atleast how I understand that it works internally the same I'm curious that there is no batch processing here and all objects need to be send via a single request which can be a lot of documents and a huge request which definitely ends in some cases in memory limit error in big amount of documents. Another thing which is not listed in the docs of replaceAll if it works with replicas as they are require for sorting, the `moveIndex` which is mention.

I need to let this go to my head if you have more information how this is supported in `Meilisearch`, `Redisearch`, `Solr` or `Typesense`, let me know.

>  Maybe a ReindexableSchemaManagerInterface?

Curious why you see this as part of SchemaManager and not part of the Indexer?

-----------

PS: Currently a migration with Zero-downtime can also be achieved manually via a read-write adapter configuration currently some more configuration and manual switching required but still possible:

**Step 1: Configure different read write indexes**

```yaml
schranz_search:
    index_name_prefix: '%env(TEST_INDEX_PREFIX)%'
    schemas:
        default:
            dir: '%kernel.project_dir%/config/schemas'
            engine: default
    engines:
        read:
            adapter: '%env(SEAL_READ_DSN)%'
        write:
            adapter: '%env(SEAL_WRITE_DSN)%'
        # multi: # would be possible to use as write adapter if still want to write into both indexes
        #   adapter: 'multi://read?adapters[]=write'
        default:
            adapter: 'read-write://read?write=write'
```

**Step 2: Configure different read write ENV**

```env
SEAL_READ_DSN=elasticsearch://127.0.0.1:9200
SEAL_WRITE_DSN=algolia://ALGOLIA_APPLICATION_ID:ALGOLIA_PRIVATE_KEY
```

**Step 3: Reindex**

Then reindex `bin/console schranz:search:reindex --engine default`

**Step 4: Use same DSN to read and write form same source**

```env
SEAL_READ_DSN=algolia://ALGOLIA_APPLICATION_ID:ALGOLIA_PRIVATE_KEY
SEAL_WRITE_DSN=algolia://ALGOLIA_APPLICATION_ID:ALGOLIA_PRIVATE_KEY
```

It's not yet documented, as I'm not yet fan of the configuration, but this way a zero downtime migration from elasticsearch to algolia is currently possible from one adapter to another. What I sure want to support is a `index_name_postfix` on `adapter` DSN level so same adapter could be reindexed.

Still doesn't solve your problem if you want todo a complete reindex as a cronjob, just wanted to mention it here that kind of zero migration from one to another DSN is supported over a manually mechanism.

But this manually mechanism is only require if the `Schema` was changed or moving to another adapter, if really just a reindex is required the following command does reindex your documents without dropping the existing index:

```bash
bin/console schranz:search:reindex --engine default --index blog
```

So that also could at current state also be used as a cronjob as it does not drop the index.

----------

I need a little bit experiment around with the aliases and replaceAll and check the other engines to get then back what the best way for reindex interface here. If you have any more hints and experience here how you currenlt ydid implement it let me know.

Its maybe also related to `bulk inserts` which should make reindex in some engines a lot faster: https://github.com/schranz-search/schranz-search/issues/24.
