### ISSUE TITLE
[Symfony] Integration configuration

### ISSUE THREAD

**Issue by alexander-schranz** [schranz-search/schranz-search#134]
We currently have 2 things which we require to configure in the Integration Bundle for Symfony. In PHP the Engine is created like this:

```php
$engine = new Engine(
    $adapter, // coming from DSN
    $schema // schema comes from different configured directories
);
```

As an application can have different engines like doctrine can have different connections, we need to keep also that configuraiton in mind.

```yaml
schranz_search:
    seal:
        prefix: '' # TODO
        schemas:
            app:
                dir: '%kernel.project_dir%/config/schemas/app'
                # added to the first engine default engine
                # a `type: ` could exist if we support in future maybe additional schema providers (attributes, xml, json, ..)
            other:
                dir: '%kernel.project_dir%/config/schemas/other'
                engine: special # a bundle maybe don't provide the engine but I can then set in my project a bundles config path to a specific engine
        engines:
            default:
                adapter: 'elasticsearch://127.0.0.1:9200'
            other:
                adapter: 'algolia://%env(ALGOLIA_APPLICATION_ID)%:%env(ALGOLIA_ADMIN_API_KEY)%'
```

@chirimoya @toflar @bmack what do you think about this configuration?

<details>
<summary>
As reference here the `doctrine.yaml` configuration:
</summary>

```yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

</details>

<details>
<summary>
The `flysystem.yaml` configuration:
</summary>

```yaml
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/%VAR_DIR%/storage/default'
```

</details>

<details>
<summary>
And the `messenger.yaml` configuration:
</summary>

```yaml
framework:
    messenger:
        transports:
            my_transport:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    auto_setup: false
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
```

</details>

**Comment by Toflar** [comment]
What exactly is `schemas`?

**Comment by alexander-schranz** [comment]
@Toflar The directories `Schema` definitions of the `indexes` are defined:

https://github.com/schranz-search/schranz-search/blob/481720f67728a8d0ba1454811ead384f1068d93f/.examples/symfony/config/schemas/blog.php#L1-L23

A Schema is generated out of them:

https://github.com/schranz-search/schranz-search/blob/481720f67728a8d0ba1454811ead384f1068d93f/packages/seal/Testing/TestingHelper.php#L21-L74

In doctrine they call it `mappings` in the orm config.

**Comment by Toflar** [comment]
Hm, I don't understand why one would have multiple schemas for an index? :D

**Comment by alexander-schranz** [comment]
One engine manage multiple Indexes and that Index definition files can be stored in different directories (project, bundles, ...).

If you define for the same `Index` multiple files (same index is based on the given name) they are merged together. This allows that a `Bundle` can provide a `Index` and you can extend the Index with more fields which are added to the that Index.

For example a bundle provides:

```php  
// vendor/my/bundle/config/schemas/blog.php

use Schranz\Search\SEAL\Schema\Field; 
use Schranz\Search\SEAL\Schema\Index; 
  
return new Index('blog', [ 
    'id' => new Field\IdentifierField('id'), 
    'title' => new Field\TextField('title'), 
    'description' => new Field\TextField('description'), 
]);
```

And a project extend that via in the project dir via:

```php  
// config/schemas/blog.php

use Schranz\Search\SEAL\Schema\Field; 
use Schranz\Search\SEAL\Schema\Index; 
  
return new Index('blog', [ 
    'author' => new Field\TextField('id', filterable: true), 
]);
```

At the end the `Engine` gets one instance of that `Index`:

```php
use Schranz\Search\SEAL\Schema\Field; 
use Schranz\Search\SEAL\Schema\Index; 
use Schranz\Search\SEAL\Schema\Schema; 

new Schema([
    'blog' => new Index('blog', [ 
        'id' => new Field\IdentifierField('id'), 
        'title' => new Field\TextField('title'), 
        'description' => new Field\TextField('description'), 
        'author' => new Field\TextField('id', filterable: true), 
    ]),
]);
```

I hope that make it for you more understandable.

**Comment by alexander-schranz** [comment]
First I thought to structure it this way:

```yaml
schranz_search:
    seal:
        engines:
            default:
                adapter: 'elasticsearch://127.0.0.1:9200'
                schemas:
                    app:
                        dir: '%kernel.project_dir%/config/schemas/app'
            other:
                adapter: 'algolia://%env(ALGOLIA_APPLICATION_ID)%:%env(ALGOLIA_ADMIN_API_KEY)%'
                schemas:
                    other:
                        dir: '%kernel.project_dir%/config/schemas/other'
```

But wanted to separate the `schemas` from the `engines` in the config so I can overwrite via:

```yaml
schranz_search:
    seal:
        schemas:
            somebundle:
                engine: other 
```

Which `engine` is managing this provided by that configured directory.

**Comment by alexander-schranz** [comment]
While testing the first configuration I will remove the `seal` prefix so this seems better at current state:

```yaml
schranz_search:
    prefix: 'my_'
    schemas:
        app:
            dir: '%kernel.project_dir%/config/schemas'
    engines:
        default:
            adapter: 'elasticsearch://127.0.0.1:9200'
```

Update: As discussed it should be `index_name_prefix`.
