### ISSUE TITLE
[Symfony] Create a Flex Recipe

### ISSUE THREAD

**Issue by alexander-schranz** [schranz-search/schranz-search#316]
A flex recipe is considered to automatically registering the bundle and provide a test configuration for Symfony.

What should a flex recipe to https://github.com/symfony/recipes-contrib

## config/packages/schranz_search.yaml

```
schranz_search:
    schemas:
        default:
            dir: '%kernel.project_dir%/config/schemas'
    engines:
        default:
            adapter: '%env(SEAL_DSN)%'
```

## config/schemas/.gitignore

Create a empty schemas directory where the user can then create it schema files

# SEAL_DSN for `.env` 

```env
SEAL_DSN=loupe://var/indexes
```

# SEAL_DSN for `.env.test`

```env
SEAL_DSN=memory://
```

# Recipe manifest.json

```json
{
    "bundles": {
        "Schranz\\Search\\Integration\\Symfony\\SearchBundle": ["all"]
    },
    "copy-from-recipe": {
        "config/": "%CONFIG_DIR%/"
    }
}
```

**Comment by ToshY** [comment]
Hey @alexander-schranz 👋 

If you'd like, I can try to create a PR for this in the recipes-contrib repo, as it doesn't seem to difficult to do with the info you've already provided.

Only thing I'm not sure if it is possible is the `.env.test`. I do not see other bundles having this configured, maybe I'm missing something (?). Instead maybe add it as a comment is an alternative.

`manifest.json`
```json
{
    "bundles": {
        "Schranz\\Search\\Integration\\Symfony\\SearchBundle": ["all"]
    },
    "copy-from-recipe": {
        "config/": "%CONFIG_DIR%/"
    },
   "env": {
        "#1": "SEAL_DSN=\"memory://\"",
        "SEAL_DSN": "loupe://var/indexes"
    },
}
```

**Comment by alexander-schranz** [comment]
@ToshY we could use `add-lines` configuration for the `.env.test` see https://github.com/symfony/recipes/pull/1239/files as example.

**Comment by ToshY** [comment]
I've created a PR: https://github.com/symfony/recipes-contrib/pull/1575. If there's anything that needs to be changed, let me know.

**Comment by dhirtzbruch** [comment]
> Only thing I'm not sure if it is possible is the `.env.test`. I do not see other bundles having this configured, maybe I'm missing something (?). Instead maybe add it as a comment is an alternative.

From other bundles, I think the standard way would be more like changing the parameters.yaml configuration to include a config specific for the `test` environment. E.g. [JMS serializer](https://github.com/symfony/recipes-contrib/blob/main/jms/serializer-bundle/4.0/config/packages/jms_serializer.yaml) uses that for providing different config between prod / dev environment.

# config/packages/schranz_search.yaml
```yaml
schranz_search:
    schemas:
        default:
            dir: '%kernel.project_dir%/config/schemas'
    engines:
        default:
            adapter: '%env(SEAL_DSN)%'

when@test:
    schranz_search:
        engines:
            default:
                adapter: 'memory://'
```
