### ISSUE TITLE
Create a Symfony Flex Recipe

### ISSUE THREAD

**Issue by elliotbruneel** [schranz-search/schranz-search#543]
The current bundle namespace is `CmsIg\Seal\Integration\Symfony`, which is not compliant with Symfony Flex. Therefore, no flex recipe is automatically generated, and the bundle is not automatically added to `bundles.php`.

ref: https://symfony.com/doc/current/bundles/best_practices.html#bundle-name

Would it be possible to move the bundle to a namespace compliant with flex conventions to enable recipe generation?

**Comment by alexander-schranz** [comment]
> Would it be possible to move the bundle to a namespace compliant with flex conventions to enable recipe generation?

Its not a requirement, somebody just require to create a Pull request to https://github.com/symfony/recipes-contrib with a metadata file like this: https://github.com/symfony/recipes-contrib/blob/aed925e50266081a2b35fbd57103922123e30f38/sulu/headless-bundle/0.1/manifest.json#L2-L4 Then flex will register the bundle correctly.

I have no plan to change things only because of flex. Do you want to create a PR to recipes-contrib containing that metadata file.

```json
{
    "bundles": {
        "CmsIg\\Seal\\Integration\\Symfony\\SealBundle": ["all"]
    },
    "copy-from-recipe": {
        "config/": "%CONFIG_DIR%/"
    }
}
```


The recipe should also contain a basic config:

```yaml
cmsig_seal:
    index_name_prefix: '%env(default::TEST_INDEX_PREFIX)%'
    schemas:
        default:
            dir: '%kernel.project_dir%/config/schemas'
            engine: default
    engines:
        default:
            adapter: '%env(SEAL_DSN)%'
```
