### ISSUE TITLE
More options for meilisearch adapter: disable typo tolerance and set language for attributes

### ISSUE THREAD

**Issue by jahrsensetence** [schranz-search/schranz-search#556]
We are trying to remove the dependency to Meili and enable to use of other search engines in future in our project. However, at the moment we want to still use meilisearch. For some attributes like product numbers we have to disable typo tolerance, also we have to enforce language for some attributes (should be German).

With the Meili symfony bundle it's just configuration:

```
                localizedAttributes:
                    - locales: ["deu"]
                      attributePatterns: ["name", "name2", "name3", "longDescription", "variant"]
                typoTolerance:
                    disableOnAttributes:
                    - 'articleNumber'
                    - 'ean'
                    - 'vendorProductNumber'
```

I see that there are no similar options (yet) in the meili adapter and I would like to add such. 

What's the best way to do this? And would you be interested in having the changes? I could form the adapter repo and keep it for myself, then when work is completed create a fork of the search repo and provide my changes as PR.

I assume, the "options" in the fields would be enough for these flags, i.e., locale and disabledTypoTolerance?
